server:
  port: 8082
spring:
  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: artemis
    embedded:
      enabled: false
  jms:
    template:
      receive-timeout: 2


---
spring:
  config:
    active:
      on-profile: jms-template, rabbitmq-template
  jms:
    template:
      receive-timeout: 3